Delete .xyz.swap (#140)
I'm pretty sure this was added unintentionally. It's a vim swap file containing:
```
Error Message
org.scalatest.exceptions.TestFailedException: Test failed because toggles have not been exercised correctly:

Flags expected but not called:

* wd.esb.features.cloud.master.cors.split.spa.btga

Flags called but not expected:

* N/A

with features:
  wd.esb.features.cloud.master.zeus.sync.lock.until.consensus -> DISABLE
  wd.esb.features.cloud.master.cors.split.spa.btga -> ENABLE
~                                                                
```